server:
  port: 8085
  servlet:
    context-path: /todo-service
spring:
  application:
    name: todo-service
  jpa:
    flyway:
      enabled: true
      locations: classpath:db/migration/common
    database: postgresql
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temps:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5556/todo_db_local?user=todo-user&password=secret"
    hikari:
      maximum-pool-size: 10
      pool-name: "hikari-cp-${spring-application-name}"

